name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: go build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - run: go test -cover -v ./...
