on: release
name: Handle Release
jobs:
  upload:
    name: Upload Artifacts
    runs-on: - misspell
    steps:
      - uses: actions/checkout@master
      - name: Upload
        uses: ./.github/actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: "mdmdirector-linux mdmdirector-darwin"
